package repository

import (
	"errors"
	"time"

	"github.com/yourusername/go_server/internal/models"
)

// Mock data for demonstration
var users = []models.User{
	{
		ID:        "1",
		Name:      "John Doe",
		Email:     "john@example.com",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
	{
		ID:        "2",
		Name:      "Jane Smith",
		Email:     "jane@example.com",
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	},
}

func (r *Repository) GetAllUsers() ([]models.User, error) {
	// TODO: Implement actual database query
	return users, nil
}

func (r *Repository) GetUserByID(id string) (*models.User, error) {
	// TODO: Implement actual database query
	for _, user := range users {
		if user.ID == id {
			return &user, nil
		}
	}
	return nil, errors.New("user not found")
}

func (r *Repository) CreateUser(user *models.User) error {
	// TODO: Implement actual database insert
	user.ID = "new-id" // In real app, this would be generated by DB
	user.CreatedAt = time.Now()
	user.UpdatedAt = time.Now()
	users = append(users, *user)
	return nil
}

func (r *Repository) UpdateUser(user *models.User) error {
	// TODO: Implement actual database update
	for i, u := range users {
		if u.ID == user.ID {
			user.UpdatedAt = time.Now()
			users[i] = *user
			return nil
		}
	}
	return errors.New("user not found")
}

func (r *Repository) DeleteUser(id string) error {
	// TODO: Implement actual database delete
	for i, user := range users {
		if user.ID == id {
			users = append(users[:i], users[i+1:]...)
			return nil
		}
	}
	return errors.New("user not found")
}
